version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build:
      context: .
      args:
        PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - db
    volumes:
    - .:/usr/src/app

  db:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - data:/data/db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

volumes: 
 data: {}