name: Lint

on: push

jobs:
  lint-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint
  lint-application:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./application
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint
